[functions.create-mercado-pago-preference]
verify_jwt = false

[functions.create-mercado-pago-pix]
verify_jwt = false

[functions.sync-mercado-pago-payment]
verify_jwt = false

[functions.mercado-pago-webhook]
verify_jwt = false
